version: '3'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    container_name: nginx-proxy-manager 
    environment:
      - TZ=Asia/Shanghai  
    labels:
      - "com.centurylinklabs.watchtower.enable=true" 
    ports:
      - 443:443
      - 80:80
      - 81:81
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      
networks:
  default:
    name: app
    driver: bridge