version: "3"

services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing  
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/data1:/data1
      - /path/to/data2:/data2
      
networks:
  default:
    name: app
    driver: bridge