version: '3'

services:
  aapanel:
    image: aapanel/aapanel
    container_name: aapanel
    environment:
      - TZ=Asia/Shanghai  
    labels:
      - "com.centurylinklabs.watchtower.enable=true" 
    ports:
      - 8886:7800
      - 21:21
      - 443:443
      - 80:80
      - 888:888
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true 
    volumes:
      - aapanel:/www
      
volumes:
  aapanel:
    name: aapanel-www

networks:
  default:
    name: app 
    external: true   