version: "3"

services:
  rathole-server:
    image: rapiz1/rathole
    container_name: rathole-server
    command: ["--server", "/app/server.toml"]
    environment:
      - TZ=Asia/Shanghai      
    labels:
      - "com.centurylinklabs.watchtower.enable=true" 
    ports:
      - 2333:2333
      # - 5202:5202
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - path/to/server.toml:/app/server.toml 
      
networks:
  default:
    name: app
    driver: bridge