version: "2.1"
services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    container_name: snapdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - snapdrop_config:/config
    # ports:
    #   - 80:80
    #   - 443:443
    restart: unless-stopped

volumes:
  snapdrop_config:
    name: snapdrop

networks:
  default:
    name: app 
    external: true   