version: '3'

services:
  openwrt:
    image: dreamwsbg/openwrt:6.0
    container_name: openwrt
    environment:
      - TZ=Asia/Shanghai  
    restart: always
    privileged: true 
    stdin_open: true
    tty: true  
    network_mode: "macnet"
    command: /sbin/init
 