version: "3"

services:
  subconverter:
    image: tindy2013/subconverter
    container_name: subconverter     
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 25500:25500
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro

networks:
  default:
    name: app
    driver: bridge