version: "3"

services:
  rathole-client:
    image: rapiz1/rathole
    container_name: rathole-client
    command: ["--client", "/app/config.toml"] 
    labels:
      - "com.centurylinklabs.watchtower.enable=true" 
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - path/to/config.toml:/app/config.toml

networks:
  default:
    name: app 
    external: true  