version: "3"

services:
  x-ui:
    image: enwaiax/x-ui
    container_name: x-ui  
    environment: 
      - TZ=Asia/Shanghai
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 54321:54321    
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true 
    volumes:
      - /path/to/appdata/db:/etc/x-ui
      - /path/to/appdata/cert:/root/cert

networks:
  default:
    name: app
    driver: bridge