version: "3"

services:
  x-ui:
    image: enwaiax/x-ui:alpha-zh
    container_name: x-ui  
    environment: 
      - TZ=Asia/Shanghai
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 54321:54321    
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true 
    volumes:
      - db:/etc/x-ui
      - cert:/root/cert

volumes:
  db:
    name: x-ui-db
  cert:
    name: x-ui-cert

networks:
  default:
    name: app 
    external: true  