version: '3.3'

services:
  plesk:
    image: buluma/debian-systemd
    container_name: plesk-debian
    environment:
      - TZ=Asia/Shanghai  
    restart: always
    privileged: true 
    #stdin_open: true
    #tty: true 
    #entrypoint: /www/start.sh
    command: tail -f /dev/null 
    ports:
        - '8880:8880' 
    tmpfs: '/tmp,/run,/run/lock'
    volumes:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
        - plesk/psa:/usr/local/psa
        - plesk/www:/var/www
        - plesk/mysql:/var/lib/mysql

       
volumes:
  plesk:
    name: plesk

networks:
  default:
    name: app 
    external: true